# Users config
user_columns:
    - user_id
    - user_name
    - user_location
    - user_birth_date
    - user_age
    - user_tags
    - user_preferences

# Talent config
talent_columns:
    - talent_id
    - talent_name
    - talent_location
    - talent_birth_date
    - talent_age
    - talent_tags
    - talent_description

# Review config
review_columns:
    - user_id
    - talent_id
    - rating
    - review
