# Users config
users_dir: data/users.csv
user_columns:
    - user_id
    - user_name
    - user_location
    - user_birth_date
    - user_age
    - user_tags
    - user_preferences

# Talent config
talents_dir: data/talents.csv
talent_columns:
    - talent_id
    - talent_name
    - talent_location
    - talent_birth_date
    - talent_age
    - talent_tags
    - talent_description

# Review config
reviews_dir: data/reviews.csv
review_columns:
    - review_id
    - user_id
    - talent_id
    - rating
    - review

locations_dir: data/reviews.csv
